spring:
  batch:
    jdbc:
      initialize-schema: always
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
    show-sql: true
  datasource:
    url: jdbc:mariadb://localhost:8080/test-database
    username: root
    password: 123456
    driver-class-name: org.mariadb.jdbc.Driver
  sql:
    init:
      mode: always
springdoc:
  use-fqn: true
  swagger-ui:
    operations-sorter: method
    tags-sorter: alpha
    doc-expansion: none
    display-request-duration: true
    show-extensions: true
    show-common-extensions: true

server:
  port: 9090
